# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ac4b334691bdc0fc3d69b0718113ae531ac7b00a9b78183d3d94e2d023e5a5f172c7c6237886e10116f456ff1e6b9898db29ad7ec80db32ae4925bd68f9e354f

test:
  secret_key_base: 38354d42ae08d5bbe0da2b27a2714b0d143a948d74f7305da9528364dc9cff0306c8f7b4a2f1e39928880dc2f11293f98ee30c53cca3757faf3e88e621c4ba63

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
